import { pgTable, serial, text, timestamp, integer, jsonb, boolean, index } from 'drizzle-orm/pg-core'

export const categories = pgTable('categories', {
  id:        serial('id').primaryKey(),
  slug:      text('slug').notNull().unique(),
  nameTr:    text('name_tr').notNull(),
  nameEn:    text('name_en').notNull().default(''),
  nameAr:    text('name_ar').notNull().default(''),
  nameRu:    text('name_ru').notNull().default(''),
  sortOrder: integer('sort_order').default(0),
  createdAt: timestamp('created_at').defaultNow(),
})

export const products = pgTable('products', {
  id:         serial('id').primaryKey(),
  slug:       text('slug').notNull().unique(),
  nameTr:     text('name_tr').notNull(),
  nameEn:     text('name_en').notNull().default(''),
  nameAr:     text('name_ar').notNull().default(''),
  nameRu:     text('name_ru').notNull().default(''),
  category:   text('category').notNull().references(() => categories.slug, { onUpdate: 'cascade' }),
  descTr:     text('desc_tr').notNull().default(''),
  descEn:     text('desc_en').notNull().default(''),
  descAr:     text('desc_ar').notNull().default(''),
  descRu:     text('desc_ru').notNull().default(''),
  images:     jsonb('images').$type<string[]>().default([]),
  model3dUrl: text('model_3d_url'),
  bg:         text('bg').default('#1c1c1f'),
  specsTr:    jsonb('specs_tr').$type<string[]>().default([]),
  specsEn:    jsonb('specs_en').$type<string[]>().default([]),
  specsAr:    jsonb('specs_ar').$type<string[]>().default([]),
  specsRu:    jsonb('specs_ru').$type<string[]>().default([]),
  maxPressure: text('max_pressure'),
  maxTemp:     text('max_temp'),
  variants:    jsonb('variants').$type<{ code: string; cins: string; connection: string }[]>().default([]),
  price:      text('price'),
  priceNote:  text('price_note'),
  seoTitleTr: text('seo_title_tr'),
  seoTitleEn: text('seo_title_en'),
  seoTitleAr: text('seo_title_ar'),
  seoTitleRu: text('seo_title_ru'),
  seoDescTr:  text('seo_desc_tr'),
  seoDescEn:  text('seo_desc_en'),
  seoDescAr:  text('seo_desc_ar'),
  seoDescRu:  text('seo_desc_ru'),
  isFeatured: boolean('is_featured').default(false),
  isActive:   boolean('is_active').default(true),
  sortOrder:  integer('sort_order').default(0),
  createdAt:  timestamp('created_at').defaultNow(),
  updatedAt:  timestamp('updated_at').defaultNow(),
})

export const contactRequests = pgTable('contact_requests', {
  id:          serial('id').primaryKey(),
  name:        text('name').notNull(),
  email:       text('email').notNull(),
  phone:       text('phone'),
  message:     text('message'),
  productSlug: text('product_slug'),
  createdAt:   timestamp('created_at').defaultNow(),
}, (table) => ({
  createdAtIdx: index('contact_requests_created_at_idx').on(table.createdAt),
}))
